name: Run Regression ðŸ§ª
on:
  pull_request:
    branches:
      - main

jobs:
  run-regression:
    runs-on: ubuntu-latest

    steps:
      - name: âœ… Checkout CÃ³digo
        uses: actions/checkout@v4

      - name: âœ… Installing java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: âœ… Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      - name: âœ… Run regression
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/regression.xml


